<div id="delivery-date">
    <strong><?php echo __('Delivery Date') ?></strong>
    <span class="price"><?=$block->getDeliveryDate() ?></span>
</div>
<div id="delivery-comment">
    <strong><?php echo __('Comment') ?>:</strong>
    <br/>
    <span class="price"><?=$block->getDeliveryComment() ?></span>
</div>
<div class="free-shipping-info" >
    <div class="step-title" data-role="title" data-bind="i18n: 'Pickup Information'"></div>
    <p class="desc" data-bind="html: getOpeningHours()"></p>
</div> 
<script type="text/javascript">
    require(
        ['jquery'],
        function($) {
            var element = $('#delivery-date').detach();
            $('.box-order-shipping-method').append(element);
            var element = $('#delivery-comment').detach();
            $('.box-order-shipping-method').append(element);
        }
    );
</script>