<?php $baseUrl = $this->getBaseUrl(); ?>
<a class="action submit primary" data-toggle="modal" href="#responsive" data-target="#responsive">
    <span>Add New Testimonial</span>
</a>
<?php
$mediaUrl = $this->getMediaUrl();
$testimonialrecords = $this->getCollection();
if ($testimonialrecords && count($testimonialrecords)) {
    ?>
<div class="testimonial-item-dv">
    <ul class="testimonial-item">
        <?php
        foreach ($testimonialrecords as $tetimonial) {
            ?>
            <li>

                <h3 class="testimonial-name"><?= $tetimonial->getData('name'); ?></h3>
                <div class="testimonial-email"><?php //echo $tetimonial->getData('email');
                ?></div>
                <div class="testimonial-image">
                    <?php $path = $tetimonial->getData('avatar_path'); ?>
                    <?php if (isset($path) && $path != ''): ?>
                        <img src="<?= $mediaUrl . $tetimonial->getData('avatar_path'); ?>" width="100"
                             height="100"/>
                    <?php else: ?>
                        <img src="<?= $this->getDefaultImage(); ?>" width="100" height="100"/>
                    <?php endif; ?>
                </div>
                <div class="testimonial-desc"><?= $tetimonial->getData('testimonial'); ?></div>
            </li>

            <?php
        }
        ?>
    </ul>
    <?php } ?>
</div>
<?php if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml(); ?></div>
<?php endif ?>
<?php
$value = $this->helper(\MageArray\Testimonials\Helper\Data::Class)->getConfig('testimonials/general/infinitescroll');
;
?>
    <script>
        require(['jquery', 'testimonialmodal'], function ($) {

        });
    </script>
<?php if ($value): ?>
    <script>
        require(['jquery', 'testimonialscroll'], function ($) {
            jQuery('.toolbar-number').css("display", "none");
            var ias = $.ias({
                container: "#maincontent",
                item: ".testimonial-item-dv",
                pagination: ".pages",
                next: ".pages .pages-item-next a"
            });
            ias.extension(new IASSpinnerExtension());
            ias.extension(new IASNoneLeftExtension({text: 'There are no more pages left to load.'}));
            ias.extension(new IASPagingExtension());
            ias.extension(new IASHistoryExtension());

        });
    </script>
<?php endif; ?>

<div id="responsive" class="modal fade bootstrap-dialog type-primary" role="dialog" tabindex="-1" data-width="760">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <div class="bootstrap-dialog-title">Add Testimonial</div>
            </div>
            <div class="modal-body">
                <?php
                $users = $this->getcustomerSession();
                $firstname = $users['firstname'];
                $email = $users['email'];
                $cid = $users['entity_id'];
                ?>
                <form method="POST" enctype='multipart/form-data'
                      action="<?= $this->getUrl('testimonials/index/post'); ?>"
                      data-hasrequired="<?= __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
                    <?= $block->getBlockHtml('formkey'); ?>
                    <?php
                    if (isset($cid) && $cid != '') {
                        ?>
                        <input type="hidden" name="customer_id" value="<?= $cid; ?>">
                        <?php
                    }
                    ?>

                    <fieldset class="fieldset">
                        <div class="field name required">
                            <label class="label" for="name"><span><?= __('Name') ?></span></label>
                            <div class="control">
                                <input name="name" id="name" title="<?= __('name') ?>"
                                       value="<?php if (isset($firstname) && $firstname != '') {
                                            echo $firstname;
                                              } else {
                                                  echo '';
                                              } ?>" class="input-text" type="text" data-validate="{required:true}"/>
                            </div>
                        </div>
                        <div class="field email required">
                            <label class="label" for="name"><span><?= __('Email') ?></span></label>
                            <div class="control">
                                <input name="email" id="email" title="<?= __('email') ?>"
                                       value="<?php if (isset($email) && $email != '') {
                                            echo $email;
                                              } else {
                                                  echo '';
                                              } ?>" class="input-text" type="text" data-validate="{required:true}"/>
                            </div>
                        </div>

                        <div class="field avatar_path">
                            <label class="label"
                                   for="avatar_path"><span><?= __('Upload Avatar') ?></span></label>
                            <div class="control">
                                <input type="file" name="avatar_path" id="avatar_path"
                                       title="<?= __('Upload Avatar') ?>"/>

                            </div>
                        </div>

                        <div class="field testimonial required">
                            <label class="label" for="testimonial"><span><?= __('Testimonial') ?></span></label>
                            <div class="control">
                                <textarea rows="4" cols="50" data-validate="{required:true}" rows="4" cols="50"
                                          name="testimonial" id="testimonial"
                                          title="<?= __('Testimonial') ?>"></textarea>

                            </div>
                        </div>

                        <div class="actions-toolbar">
                            <div class="primary">
                                <button type="submit" title="<?= __('Submit') ?>" class="action submit primary">
                                    <span><?= __('Submit') ?></span>
                                </button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>