<?php
$helper = $this->helper("Ves\Brand\Helper\Data");

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance(); 

$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$store = $storeManager->getStore();
  $baseUrl = $store->getBaseUrl();
// $baseSecureUrl = $store->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_WEB, true);



?>
<div class="ves-block block brand-searchform">
	<div class="block-title">
		<strong><?php echo __('Search Brand'); ?></strong>
	</div>
	<div class="block-content">
		<form method="get" class="search-form" action="<?php echo $helper->getSearchFormUrl(); ?>" data-mage-init='{"validation":{}}'>
			<input type="text" class="search-field required-entry" placeholder="<?php echo __('Search brands here…'); ?>" value="<?php echo $helper->getSearchKey() ?>" name="s" title="<?php echo __('Search for:'); ?>">
			<button type="submit" class="search-submit"><i class="fa fa-search"></i></button>
			<a class="action primary" href="<?php echo $baseUrl; ?>/brand" style="margin-top:10px;">Clear</a>
		</form>
	</div>
</div>