 
<div class="htb-main pad-main">
<div class="block-title-main">
<h2><span>Testimonial</span></h2>
<div class="title-border"></div>
</div>
  
<?php $baseUrl = $block->getBaseUrl(); ?><?php
$mediaUrl = $block->getMediaUrl();
$testimonialrecords = $this->getCollection();
if ($testimonialrecords && count($testimonialrecords)) {
    ?>
    <div class="testimonialslider">
        <div class="slides">
            <?php
            foreach ($testimonialrecords as $tetimonial) { ?>
                <div class="testimonial-widget item">
                    <div class="quote">
                        <p><?= /* @noEscape */ $tetimonial->getData('testimonial'); ?></p>
                    </div>
                    <div class="student">
                        <div class="photo">
                            <?php $path = $tetimonial->getData('avatar_path'); ?>
                            <?php if (isset($path) && $path != ''): ?>
                                <img src="<?= /* @noEscape */ $mediaUrl . $tetimonial->getData('avatar_path'); ?>"
                                width="100" height="100"/>
                            <?php else: ?>
                                <img src="<?= /* @noEscape */ $block->getDefaultImage(); ?>" width="100" height="100"/>
                            <?php endif; ?>
                        </div>
                        <p><?= /* @noEscape */ $tetimonial->getData('name'); ?></p>
                    </div>
                </div>

                <?php
            }
            ?>
        </div>
    </div>
    <?php
}
?>
<?php if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom"><?= /* @noEscape */ $block->getPagerHtml(); ?></div>
<?php endif ?>
<div class="add-new-testimonial" style="display:none">
    <a class="action submit primary" data-toggle="modal" href="#responsive">
        <span>Add New Testimonial</span>
    </a>
</div>

<script>
    require([
        'jquery',
        'testimonialSlider', 'testimonialmodal'
    ], function ($) {
       $(".testimonialslider .slides").owlCarousel({
            autoPlay: 5000,
            items: 1,
            itemsDesktop: [1199, 1],
            itemsTablet: [768, 1],
            itemsDesktopSmall: [979, 1],
            itemsMobile: [750, 1],
            pagination: true,
            navigation: false
        });
    });
</script>
<div id="responsive" class="modal fade bootstrap-dialog type-primary" tabindex="-1" data-width="760">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <div class="bootstrap-dialog-title">Add Testimonial</div>
            </div>
            <div class="modal-body">            <?php $users = $block->getcustomerSession();
                $firstname = $users['firstname'];
                $email = $users['email'];
                $cid = $users['entity_id']; ?>
                <form method="POST" enctype='multipart/form-data'
                      action="<?= /* @noEscape */ $block->getUrl('testimonials/index/post'); ?>"
                      data-hasrequired="<?= /* @noEscape */ __('* Required Fields') ?>"
                      data-mage-init='{"validation":{}}'>                    <?php if (isset($cid) && $cid != '') { ?>
                        <input type="hidden" name="customer_id"
                               value="<?= /* @noEscape */ $cid; ?>">                            <?php } ?>
                    <fieldset class="fieldset">
                        <div class="field name required"><label class="label"
                                                                for="name"><span><?= /* @noEscape */ __('Name') ?></span></label>
                            <div class="control"><input name="name" id="name" title="<?= /* @noEscape */ __('name') ?>"
                                                        value="<?php if (isset($firstname) && $firstname != '') {
                                                           /* @noEscape */ echo $firstname;
                                                               } else {
                                                                   echo '';
                                                               } ?>" class="input-text" type="text"
                                                        data-validate="{required:true}"/></div>
                        </div>
                        <div class="field email required"><label class="label"
                                                                 for="name"><span><?= /* @noEscape */ __('Email') ?></span></label>
                            <div class="control"><input name="email" id="email" title="<?= /* @noEscape */ __('email') ?>"
                                                        value="<?php if (isset($email) && $email != '') {
                                                          /* @noEscape */  echo $email;
                                                               } else {
                                                                   echo '';
                                                               } ?>" class="input-text" type="text"
                                                        data-validate="{required:true}"/></div>
                        </div>
                        <div class="field avatar_path"><label class="label"
                                                              for="avatar_path"><span><?= /* @noEscape */ __('Upload Avatar') ?></span></label>
                            <div class="control"><input type="file" name="avatar_path" id="avatar_path"
                                                        title="<?= /* @noEscape */ __('Upload Avatar') ?>"/></div>
                        </div>
                        <div class="field testimonial required"><label class="label"
                                                                       for="testimonial"><span><?= /* @noEscape */ __('Testimonial') ?></span></label>
                            <div class="control"><textarea rows="4" cols="50" data-validate="{required:true}" rows="4"
                                                           cols="50" name="testimonial" id="testimonial"
                                                           title="<?= /* @noEscape */ __('Testimonial') ?>"></textarea></div>
                        </div>
                        <div class="actions-toolbar">
                            <div class="primary">
                                <button type="submit" title="<?= /* @noEscape */ __('Submit') ?>" class="action submit primary">
                                    <span><?= /* @noEscape */ __('Submit') ?></span></button>
                            </div>
                        </div>
                    </fieldset>
                </form>
            </div>
        </div>
    </div>
</div>
</div>